services:
  codex-beta:
    build:
      context: .
      target: production
    image: codex-beta:production
    command: ["node", "dist/index.js"]
    environment:
      NODE_ENV: production
      CODEX_BETA_LOG_LEVEL: info
    volumes:
      - codex-config:/app/config
      - codex-logs:/app/logs
    ports:
      - "8080:8080"
    restart: unless-stopped

  codex-beta-dev:
    build:
      context: .
      target: development
    image: codex-beta:development
    command: ["sh", "-c", "npm install && npm run dev"]
    environment:
      NODE_ENV: development
      CODEX_BETA_LOG_LEVEL: debug
    volumes:
      - ./:/app
      - codex-config:/app/config
      - codex-logs:/app/logs
    profiles: ["dev"]
    tty: true

volumes:
  codex-config:
  codex-logs:
